### ISSUE TITLE
Comparison operations type coerce between arrays and numbers

### ISSUE THREAD

**Issue by labwarek** [aleReimondo/S8#10]
[Array new < 5] evaluates to true. The optimization that enables this behavior is incorrect and should be disabled. 

#< and related messages are not even implemented on Array.

**Comment by aleReimondo** [comment]
Note that disabling this optimizations impose impact in perfomance (same situation as numbers in math ops).

**Comment by labwarek** [comment]
Disabling this optimization is important for correctness of the system. Correctness is more important than speed.

In the places where you are sure of the other type and performance issues have been found via profiling, you would be able to write those methods by hand with the optimization applied. Base S8 should be a regular and correct. If a user applies an optimization to reduce correctness, that is their choice but it should not be in the base.
