### ISSUE TITLE
SequenceableCollection>>#indexOf:ifAbsent:

### ISSUE THREAD

**Issue by labwarek** [aleReimondo/S8#12]
In S8 core, #indexOf:ifAbsent: returns the last index that is equivalent to the element. This behavior is the opposite of the spec and other Smalltalk dialects.

The first index that is equivalent to the element should be returned.

**Comment by aleReimondo** [comment]
corrected
#( 1 2 34 5 1 8) indexOf: 1 ifAbsent: []
returns 1
