### ISSUE TITLE
Web development environment

### ISSUE THREAD

**Issue by labwarek** [aleReimondo/S8#13]
In Chrome, I'm unable to scroll in the methods pane of the code browser. I am able to scroll in the class pane. Chrome 51.0.2704.84 (64-bit).

In Safari, I'm able to scroll in both panes. If I open a second window, I'm unable to move either window. The new window opens behind the first and I'm unable to get focus on that window. Safari 9.1.1 (11601.6.17).

Both are running in OS X 10.11.5.

**Comment by aleReimondo** [comment]
Same Chrome and OSX version, the issue do not happen here.
Tested on http://u8.smalltalking.net/profile/aleReimondo/239
    browsing Object instance messages.
Try deleting history of Chrome to ensure you have the last version of the U8 tools.

On Safari (same version) it also works OK the scrolling for Object methods.

Confirmed the issue when openening a second window.
There is an error in HTMLDesktop>>#mouseDown: 
   #mustBeNumber  in zIndex

**Comment by aleReimondo** [comment]
Issue in zIndex was related with recent changes in validating number arguments (in compare).
Changed widgets impl. to force numbers in DOM's zIndex property.
