### ISSUE TITLE
Objective-C NSTaggedPointerString does not convert to Smalltalk String

### ISSUE THREAD

**Issue by CGRG1967** [aleReimondo/S8#14]
NSFileManager>>#contentsOfDirectoryAtPath: returned an NSArray. When calling _#asArray,_ the returned Array instance contained a JSCocoa box object instead of Strings. This object should be a string but it looks like the conversion from **NSTaggedPointerString** was not handled transparently (NSTaggedPointerString is a subclass of NSString).
Workaround: 
_(NSFileManager>>#contentsOfDirectoryAtPath:  aPath ) asArray collect: [ :each | each toString ]._

**Comment by aleReimondo** [comment]
NSArray>>#asArray is implemented using enumeration (with S8BlockAdaptor).
Arguments in ObjectiveC block and method callbacks are native objects.
The native handle must be wrapped/converted to S8 objects before use, and only when needed.
In case of handles to objC instances of NSString (& subclasses) the handle can be converted to S8 String sending #toString to the handle.
