### ISSUE TITLE
Number optimizations change semantics

### ISSUE THREAD

**Issue by labwarek** [aleReimondo/S8#2]
The binary selector optimizations applied when either a receiver or an argument are numbers are invalid. An expression such as 'Array new + 5' returns 5. The #+ message is not defined for Array instances so it should result in a #doesNotUnderstand:. (Or the current failed message send mechanism.)

These optimization are valid when both the receiver and the argument are numbers. In this case, the possible performance boost would be negligible.

**Comment by aleReimondo** [comment]
Commented arith inlines from Compiler>>#defaultOptimizationMap

**Comment by aleReimondo** [comment]
Next version of all platforms where S8 run will have this changes included.
