### ISSUE TITLE
Number arithmetic operations

### ISSUE THREAD

**Issue by labwarek** [aleReimondo/S8#3]
Arithmetic operations defined in Number result in strange behavior. The method defines a type coercing addition. This means that something like '5 + Array new' returns the value 5.

This should be an error.

**Comment by labwarek** [comment]
This bug along with #2 apply to the comparison operations as well. 'Array new > 5' should result in an error instead of false. #< for this case returns true.

**Comment by aleReimondo** [comment]
Checks added to Number
