### ISSUE TITLE
Assignment to self, nil, true, and false

### ISSUE THREAD

**Issue by labwarek** [aleReimondo/S8#6]
The S8 compiler allows a user to assign to self, nil, true, and false. The assignment to true and false will fail at runtime. The assignment to self and nil will succeed and cause issues within the runtime.

Self, nil, true, and false should be treated as constant variables.

**Comment by aleReimondo** [comment]
S8 (as most Smalltalk environment) promotes experimentation and reduced costs to apply innovation.
As an open system a change can be made at any corner of the system.
It is part of learning to produce effective changes. e.g. if I change an object by other that can´t work as the old, there will be problems in that part of the system.

As an object environment, Smalltalk objects use names to direct messages.
An object know other objects (by name) to send messages collaborating in the resolution of a problem imposed by undestanding a message sent.
In an object system, there are objects (known  by name in a context) and messages. Nothing more.
The concepts of "variable" and constant are residues of the past, where memory was undestood as part of the (closed) system design, and memory contents varies...
(part of current smalltalks still use the "variable" concept as a residue of the roots in programming languages of the 70's)

In an object system nothing "varies". Object refer to other objects with the same names...
And assignment is assignment of a name to another object. It is simple, atomic, fast and do not depend of the "size of objects".

So, we can change the object known in a context by a name in any method.
The impact of the assignment depend on the new object.
It it can act as the old object there is no risk of failure.

The paragraphs states above are aligned with the vision we have in S8, and today there are multiple points of view about Smalltalk, what it is and what it will be in the future... We respect other POVs and we try to help other smalltalkers realize their views (Smalltalk is not it's contents, nor the definition of the classes,...).

So, how we can enhance teh compiler to check for assignments that we dont want to permit in a number of classes?
In current published version, the compiler generates an event when generating code to assign to a name. SO it is simple to hook there and produce an error, or any other treatment of the event.
If the event is not handled, default behavior will be to let the assignment happen.

See the following code to implement the requested verification while compiling method of a class:

! AssignmentTest class methodsFor: #compiling !
compiler
	" Return a compiler for receiver's source code. "

	^super compiler
		when: #acceptAssignmentTo: do: [:node| | varName |
			varName := node value.
			(#( #super #self #nil #true #false ) includes: varName)
				ifTrue: [ self error: 'Can´t asign to ',varName  ].
		];
		yourself! !

The changes has been uploaded to U8 service, and will be available in all platforms where s8 runs asap.
