### ISSUE TITLE
Recent changes in the javascript vm ES6 (chrome/opera tested) break Behavior>>#constructorName

### ISSUE THREAD

**Issue by ghost** [aleReimondo/S8#9]
**Context:**
Since the update of the latest version of chrome (today), I have problems with the export of s8 categories to .js files. When loading the file, multiple errors occurs in console about a variable called 'result'.

**Problem:**
S8 Test
Evaluate in a workspace (http://u8.smalltalking.net/profile/aleReimondo/239/index.html):

(Object allSubclasses select: [:each | each constructorName = 'result' ]) size -> 260.

The #constructorName of many classes return 'result', What is wrong, in most case should return nil.

Then the exporter adds an erroneous line to js files (see Exporter >> #defaultRequirementsFor: ).

Javascript test:
result = function(){};
result.name <- return 'result' (the name of the variable is the name of the function now)

In previous version of javascript vm, with this assignation, the name of the function remains undefined.

**Cause:** 
Recent changes in the funcionality of javascript vm to because ES6.
See: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/name
"The name property returns the name of a function, or (before ES6 implementations) an empty string for anonymous functions"

**Possible solution?:**
in the boot.js. function: st.fnInSpec, may be: ?
result = undefined || function(){}; 
result.name <- return undefined 

but it is a bit tricky...

Claudio

**Comment by aleReimondo** [comment]
boot is generating an internal name for the s8 constructor, and it is considered in Behavior>>#constructorName
